### ISSUE TITLE
[Regression] Creating Workspaces is currently broken

### ISSUE THREAD

**Issue by ralf1307** [martin-pabst/Online-IDE#14]
The server returns {success: false, message: "Not logged in"} on trying to create a workspace.

Bug discovered by: @ThatVillagerGuy

**Comment by ralf1307** [comment]
Creating a new workspace via /createOrDeleteFileOrWorkspace is broken,
Creating it via /attachWorkspaceToRepository does work

**Comment by martin-pabst** [comment]
@ralf1307 , @ThatVillagerGuy: Thank you for reporting this error! It's now fixed.
