### ISSUE TITLE
Front-end problem during save & exit

### ISSUE THREAD

**Issue by ThatVillagerGuy** [martin-pabst/Online-IDE#15]
When quitting through the save end exit button, some elements of the IDE are still visible, for example the scaling points and parts of the console.
![image](https://user-images.githubusercontent.com/53975292/118409586-5b18e680-b68b-11eb-8846-6ca4b3dc7690.png)

I also had some problems saving my project earlier (it hadn't been saved after multiple minutes), but that might be because it was too much at once.

**Comment by martin-pabst** [comment]
I did a server restart at 20:08, this caused your problems on saving you project. Sorry!
Thank you for reporting the issue concerning visibility of gui elements after logout! I'll see to them tomorrow.

**Comment by martin-pabst** [comment]
Front-end problems fixed.
