### ISSUE TITLE
Collision detection fails after world scrolling

### ISSUE THREAD

**Issue by Knorrke** [martin-pabst/Online-IDE#17]
My school class and I are currently building a jump and run game with the editor and noticed that collision detection stops working after transforming the World (e.g. `move` or `rotate`).

I think the problem is, that `hitPolygonDirty` isn't set when moving the world, since removing the check in the following line resolves the issue:
https://github.com/martin-pabst/Online-IDE/blob/d45b54b59b48d2dd9b5da172792c7ef2b96bf09c/src/client/runtimelibrary/graphics/Shape.ts#L741

I didn't find an easy way to update the `hitPolygonDirty` flag, do you have an idea?

## Test example
Some code to test this (slightly changed from https://learnj.de/doku.php?id=api:documentation:spiele:worldtransformations):
Rectangles colliding with the ship should get deleted. With Line 40 `getWorld().move(-dx, -dy)` the collisions don't work, after removing the line it does work again.
```java
World world = new World(600, 500);
ScrollingDemo sd = new ScrollingDemo();

class ScrollingDemo extends Actor {

   Sprite ship;
   int time = 0;
   Group rs = new Group();

   ScrollingDemo() {
      super();
      
      double w = 10000;

      for(int i = 0; i < 500; i++) {
         
         double x = Math.random() * w - w / 2;
         double y = Math.random() * w - w / 2;
         
         Rectangle r = new Rectangle(x, y, Math.random() * 300 + 100, Math.random() * 300 + 100);
         r.rotate(Math.random() * 180);
         r.setFillColor(Color.randomColor(100), Math.random() * 0.5 + 0.5); 
         rs.add(r);
      }

      ship = new Sprite(400, 300, SpriteLibrary.Ship_1, 0);
      ship.scale(0.3);
      ship.rotate(90);
      getWorld().scale(0.3, ship.getCenterX(), ship.getCenterY());
   }

   public void act() {
      time++;

      double v = 6;
      double dx = v * Math.cos(ship.getAngle() * Math.PI / 180);
      double dy = -v * Math.sin(ship.getAngle() * Math.PI / 180);

      ship.move(dx, dy);
      getWorld().move(-dx, -dy);
      for(Shape s : ship.getCollidingShapes(rs)) {
         s.destroy();
      }

      double centerX = ship.getCenterX();
      double centerY = ship.getCenterY();

      if(isKeyDown(Key.ArrowLeft)) {
         ship.rotate(2);
      }

      if(isKeyDown(Key.ArrowRight)) {
         ship.rotate(-2);
      }

      if(time % 10 == 0) {
         new Circle(centerX, centerY, 20);
         ship.bringToFront();
      }
   }
}
```

**Comment by martin-pabst** [comment]
Thank you for this extremely helpful description. Your guess (hitPolygonDirty-Flag) was correct and helped a lot to fix the error.

**Comment by Knorrke** [comment]
Thank you for the fast fixes, that's amazing :heart: 
Wish you nice holidays :)
