### ISSUE TITLE
WorldScaling applied on large resolutions break Groups.

### ISSUE THREAD

**Issue by ralf1307** [martin-pabst/Online-IDE#18]
I dont know where the issue is, but with the introduction with the commits that scale to half the resolution on high custom resolutions breaks Groups in a weird way.
-> Groups are displaced and dont scale correctly.

**Comment by martin-pabst** [comment]
I introduced downscaling as Chromes' performance dropped significantly with large canvas sizes. Could you write a simple test program to reproduce the issue?

**Comment by ralf1307** [comment]
```java
public class Test extends Group {
   World w = new World(800, 1400);

   Test() {
      super(new Rectangle(10, 200, 300, 1300));
      new Rectangle(400, 0, 300, 1400).setFillColor(Color.red);;
   }


   protected void act() {
      
   }
}
new Test();
```

**Comment by ralf1307** [comment]
![Hier Firefox](https://user-images.githubusercontent.com/46164027/121775155-2c0c6c80-cb86-11eb-9bd3-884fc27bd613.png)
(Leider funktioniert gerade Chromium gerade fuer mich nicht.)

**Comment by martin-pabst** [comment]
Hello Ralph,
thank you! Your test program helped a lot to locate and fix the bug!
