### ISSUE TITLE
More problems regarding groups and world scaling

### ISSUE THREAD

**Issue by ThatVillagerGuy** [martin-pabst/Online-IDE#19]
The position of the group still seems to be off by quite a bit with a custom world size

```
new Test();
public class Test extends Actor {
   World world = new World(800, 1600);
   Group g = new Group();
   public Test() {
      super();
      g.add(new Rectangle(400, 1500, 50, 50));
      println(g.getCenterX());
      println(this.getWorld().getWidth());
      
   }
}
```
Expected output:
400
800

Actual output:
850
800

**Comment by martin-pabst** [comment]
You put your finger in a wound, indeed :-)
Thank you for your test program! Now it yields the correct output: 425 (center of group == center of rectangle), 800.
I did a complete redesign of the world transformation system which not only fixed this bug but also improved performance and simplified the code.
I hope nothing broke ;-)
