### ISSUE TITLE
Please add a License file!

### ISSUE THREAD

**Issue by ralf1307** [martin-pabst/Online-IDE#2]
Ohne Open-Source oder Freie-Software Lizenz andere Leute dürfen den Code nicht nutzen oder den anschauen aufgrund der Standard-Copyright Gebung. Leider reicht die Erwähung der [MIT-Lizenz](https://choosealicense.com/licenses/mit/) nicht, sonder es braucht eine extra Datei mit dem Lizenztext.

Und vielen Dank das Sie sich dafür entschieden haben die Embedded-Variante offen zu veröffentlichen

Mit freundlichen Grüßen
Ralf Rachinger

**Comment by martin-pabst** [comment]
Ist erledigt!
