### ISSUE TITLE
isOutsideView broken with high resolutions

### ISSUE THREAD

**Issue by ralf1307** [martin-pabst/Online-IDE#21]
```java
public class TestRect extends Rectangle {
   TestRect() {
      super(Math.random() * (getWorld().getWidth() + 1), 0, 90, 100);
   }

   public void act() {
      if(isOutsideView()) {
         destroy();
         return;
      }

      move(0, 5);
   }
}
new World(800, 2000);
while(true) {
   new TestRect();
}
```

**Comment by ralf1307** [comment]
https://github.com/martin-pabst/Online-IDE/blob/b42e33a9e2ae8e7bae66a86eaf794c6b972f0b83/src/client/runtimelibrary/graphics/Shape.ts#L991

The var screen has the real coordinates of the world, not the scaled right version.

**Comment by martin-pabst** [comment]
You nailed it!
I hope there aren't any more errors coming from the huge bugfix last weekend.
Thank you, again!
