### ISSUE TITLE
Ellipsis in enum-constructor wont work

### ISSUE THREAD

**Issue by ralf1307** [martin-pabst/Online-IDE#28]
```java
public enum Test {
   t(12, 53, 34)

   private Test(int... i) {
      println(i[0]);
   }
}

// Sample function for the interpreter to run
println("test");
```

The problem is, that 12, 53 and 34 just get pushed to the stack and not get grouped together to an array like the callers of an ellipsis method do (with makeEllipsisArray).
I think it needs a fix in processEnumConstructorCall in CodeGenerator to check for ellipsis.

**Comment by martin-pabst** [comment]
Thank you!
 -> Bug is fixed.
