### ISSUE TITLE
Float.isNan() doensn't works

### ISSUE THREAD

**Issue by Informa-Tiger** [martin-pabst/Online-IDE#3]
We're working with your online IDE in our lessons. I noticed, that `Float.isNaN` will always return `false`. This happens because in java- or typescript `NaN == NaN` is `false`. I think, you should change the line
https://github.com/martin-pabst/Online-IDE/blob/ced1945516c753d848feca0ffde337e44725b4ae/src/client/compiler/types/boxedTypes/FloatClass.ts#L131
 to
```typescript
 return isNaN(parameters[1].value); 
```
The same should be done here: https://github.com/martin-pabst/Online-IDE/blob/ced1945516c753d848feca0ffde337e44725b4ae/src/client/compiler/types/boxedTypes/FloatClass.ts#L137

**Comment by martin-pabst** [comment]
Thank you!
Your bugFix-suggestions are spot on.

This testcase now works:
```
float a;
a = Math.sqrt(-1);
println(a);
println(Float.isNaN(a));

```
