### ISSUE TITLE
Multiple calls of super(...) possible 

### ISSUE THREAD

**Issue by mafeige** [martin-pabst/Online-IDE#31]
super() does not have to be the first statement of a subclass constructor.
Even multiple calls of super-constructors are possible.

Example:

new Pferd();

public class Pferd extends Tier{
   public Pferd() {
      // implicit call: super()
      setName("Kleiner Onkel");
      super("Jolly Jumper");
      super("Fury");
   }
}

public class Tier{
   private String name;
   public Tier() {
      setName("N.N.");
   }
   public Tier(String name) {
      setName(name);
   }
   public void setName(String neuerName) {
      name = neuerName;
   }
}

**Comment by martin-pabst** [comment]
Thank you for reporting!
-> Fixed.
