### ISSUE TITLE
Websocket: onOtherClientsFound: ownIndex by one too large

### ISSUE THREAD

**Issue by ralf1307** [martin-pabst/Online-IDE#34]
client.Index in L348 in onClientsFound is one large than the position in the array the client recieves.

I think, this is a server fault.

**Comment by martin-pabst** [comment]
onOtherClientsFound returns an array with all **other** clients (not own client!) in it. client.Index is **no** index into this array. WebSocketClient.index is indeed no index but only a unique number.
I renamed WebsocketClient.getIndex to WebsocketClient.getNumber and renamed second parameter in Websocket.onClientsFound to "number".
