### ISSUE TITLE
Move `@types/*` dependencies to devDependencies

### ISSUE THREAD

**Issue by Myzel394** [martin-pabst/Online-IDE#36]
"@types/*" dependencies are only required for Typescript. I would recommend moving them into the `devDependencies` (that's where they are usually). However, this project doesn't seem to be a Typescript project, why are they installed at all?

**Comment by martin-pabst** [comment]
Thank you for your suggestion! -> Moved "@types/*" dependencies to `devDependencies`.
This project is indeed mainly written in typescript (see folder src/client/...).
