### ISSUE TITLE
Log in loading animation keeps playing after failed log in attempt

### ISSUE THREAD

**Issue by krakeen06** [martin-pabst/Online-IDE#37]
As a registered user, when you input wrong user credentials while logging into the web service, the log in animation keeps playing even though the log in attempt has been concluded unsuccessfully.

Expected behaviour: the log in animation stops after the log in attempt has failed.

Actual behaviour: the log in animation keeps playing.

Device information: Windows 11, Chrome 97.0.4692.99

**Comment by martin-pabst** [comment]
Thank you! -> Bug fixed.
