### ISSUE TITLE
Error in `executeNode`

### ISSUE THREAD

**Issue by Informa-Tiger** [martin-pabst/Online-IDE#4]
Some time ago I found another error.
I ran the following code:
``` java
float myfloat = 1.0;
float[] test = { myfloat };
test[0] = 2.0;
println("myfloat: " + myfloat);
```
and to my suprise the output wasn't
```
myfloat: 1
```
like I expected, but actually:
```
myfloat: 2
```
 I sent it to my teacher Ms. Roth, but I don't know whether she has already reported you that bug. After looking in your code, I could find out, that the bug is probably caused by an error in the method `executeNode` in [./src/client/interpreter/Interpreter.ts](https://github.com/martin-pabst/Online-IDE/tree/master/src/client/interpreter/Interpreter.ts). 
https://github.com/martin-pabst/Online-IDE/blob/ef1b0f4d939f3cc6279acd53d2b85ed38f4c3ace/src/client/interpreter/Interpreter.ts#L1311-L1315
Maybe line 1313 should be changed to something like:
```ts
     let values: Value[] = stack.splice(stackTop + 1, node.numberOfElementsToAdd).map(tvo => ({type: tvo.type, value: tvo.value}));
```
Then the the type-value-object of the variable isn't the same like the type-value-object in the array and it's value wouldn't change any more, when the value of the other one is changed.

**Comment by martin-pabst** [comment]
Thank you very much, again!

You nailed it!
