### ISSUE TITLE
ein paar Anmerkungen

### ISSUE THREAD

**Issue by rozek** [martin-pabst/Online-IDE#42]
Zunächst einmal vielen Dank für diese tolle Java-Umgebung - dahinter steckt ganz offensichtlich eine ganze Menge Arbeit.

Beim Versuch, die Online-IDE auf eine eigene Webseite zu packen, bin ich jedoch auf eine Reihe von Problemen gestoßen:

- "EmbeddedStarter.ts" lädt eine Datei "assets/spritesheet.json" - relativ zum Verzeichnis mit der aktuellen HTML-Datei, nicht aber relativ zum Installationsort der Online-IDE. Eine mögliche Abhilfe scheint wohl zu sein, neben "window.monacoEditorPath" auch noch "window.javaOnlineDir" zu setzen (und "window.monacoEditorPath" relativ dazu)
- von "javaOnlineEmbedded.css" werden eine ganze Reihe von Fonts aus dem "assets"-Verzeichnis angefordert, die dort aber nicht liegen und auch nicht im Repository zu finden sind
- "MainEmbedded.ts" liefert in Zeile 217 einen "TypeError: Cannot read properties of null (reading 'model')". Mangels Zeit konnte ich dem Fehler noch nicht näher auf den Grund gehen

Für einen Fehler in der Beschreibung werde ich gleich einen (winzigen) Pull Request stellen - weitere falls ich die o.g. Fehler beheben kann (soweit es meine Zeit erlaubt)

**Comment by rozek** [comment]
zu den Fonts:
- gemäß https://fonts.google.com/attribution stehen die Fonts unter Apache 2.0 Lizenz
- ich habe die Fonts gerade selbst heruntergeladen und in meinen Fork integriert, aber natürlich werde ich gerne auch die Variante ohne externe Fonts ausprobieren

zu "window.javaOnlineDir": dieser Trick ist ja durchaus legitim, aber in den Docs wird nur "window.monacoEditorPath" erwähnt

**Comment by martin-pabst** [comment]
Vielen Dank für den Hinweis wegen `window.javaOnlineDir`. Ich habe die Dokumentation auf den neuesten Stand gebracht. Danke auch für die Beschreibung der Ursache der `NullpointerException`. Ich habe die Änderung in `MainEmbedded.ts` entsprechend korrigiert.

**Comment by rozek** [comment]
Guten Morgen!

Haben Sie auch neu gebaut? Die Dateien in js.webpack scheinen unverändert zu sein...

**Comment by martin-pabst** [comment]
Danke für den Hinweis!
Ich habe um ca. 21:00 Uhr neu gebaut und gepusht, GitHub schreibt bei den Dateien aus js.webpack: "vor 11 Stunden". 

Um sicherzugehen, dass alle zum Build nötigen Dateien vorhanden sind habe ich nochmal frisch "von Null an" ausgehend vom Stand im Repository gebaut. Dabei konnte ich den von Ihnen beobachteten Fehler nachvollziehen. Es lag am fehlenden assets/fonts-Ordner. Ich habe ihn nun doch ins Repository gepusht, so dass der Build bei mir jetzt ohne Fehlermeldung funktioniert:

 - Neueste Node-LTS-Version installiert (16.14.2)
- git clone
- npm install
- typescript build (Terminal -> Run Build Task... in VSC)
- npx webpack

Ich hoffe, dass ich am Wochenende noch etwas Zeit für das Projekt finde, dann werde ich die den Test auch mit der Current-Version von Node (17.7.2) wiederholen um den zweiten bei Ihnen aufgetretenen Fehler zu beheben.

**Comment by rozek** [comment]
Guten Morgen!

Vielen Dank für Ihre Mühe!

**Comment by rozek** [comment]
kann es sein, dass im "assets"-Ordner noch der Unterordner mit den "mp3"-Dateien fehlt?

**Comment by martin-pabst** [comment]
Die mp3-Dateien habe ich zwar alle entweder selbst aufgenommen oder aus Quellen mit freier Lizenz, bei letzteren bin ich mir aber noch nicht sicher genug. Ich möchte zuerst alle mp3-Dateien durch eigene Aufnahmen ersetzen bevor ich sie auf GitHub veröffentliche.
