### ISSUE TITLE
kann man auch zu LearnJ beitragen?

### ISSUE THREAD

**Issue by rozek** [martin-pabst/Online-IDE#44]
falls ja: wie stellt man Korrekturen bzw. Erweiterungen am besten bereit? (ein passendes GitHub Repo habe ich nicht gefunden)

**Comment by martin-pabst** [comment]
Hallo Herr Rozek,
grundsätzlich freue ich mich über Beiträge zu Lernj/Online-IDE, ich muss aber zugeben, dass ich noch keine Erfahrung im Führen eines Open-Source-Projektes auf GitHub habe. Derzeit geht es mit der Online-IDE etwas langsamer voran, weil ich die [SQL-IDE](https://github.com/martin-pabst/SQL-Online) bis zum Ende des Schuljahres fertigstellen möchte. Danach würde ich den Compiler der Online-IDE gerne von Grund auf neu schreiben (beim zweiten Mal weiß man vieles besser...) und dabei auch ein Plugin-System schaffen, mit dem jeder eigene "Java"-Bibliotheken zur Laufzeitumgebung hinzufügen kann.
Herzliche Grüße
Martin Pabst

**Comment by rozek** [comment]
Dann wünsche ich erst einmal viel Erfolg bei der weiteren Entwicklung!
