### ISSUE TITLE
FYI: Online-IDE auf GitHub Pages

### ISSUE THREAD

**Issue by rozek** [martin-pabst/Online-IDE#45]
Falls es Sie interessiert: da ich plane, meine Erstsemester (die an der HfT Stuttgart u.a. Java erlernen) auf LearnJ und die Online-IDE hinzuweisen, die Studenten aber eher mit GitHub arbeiten und dort ggfs. auch eigene Arbeiten veröffentlichen sollen, habe ich ein wenig herumexperimentiert um herauszufinden, wie man die "Embedded IDE" in "GitHub Pages" integriert.

Die gefundene Vorgehensweise finden Sie in einem [GitHub Repository](https://github.com/rozek/online-ide-within-github-pages) erklärt, das Ergebnis können Sie auf der zugehörigen [GitHub Page](https://rozek.github.io/online-ide-within-github-pages/) einsehen.

Nochmals vielen Dank für Ihre großartige Arbeit!

**Comment by martin-pabst** [comment]
Hallo Herr Rozek,
die Idee, die Embedded-Online-IDE in GitHub Pages zu nutzen, finde ich genial! Darf Ich Ihr GitHub Repository und die Beschreibung auf [https://www.embed.learnj.de/createwrapper.html](https://www.embed.learnj.de/createwrapper.html) verlinken?
Viele Grüße
Martin Pabst

**Comment by rozek** [comment]
Guten Abend!

Sofern es meine Zeit erlaubt, werde ich (ausgewählte) Java-Beispiele für meine Erstsemester auch über ein [GitHub Repository](https://github.com/rozek/online-ide-examples) bzw. die zugehörige [GitHub Page](https://rozek.github.io/online-ide-examples/) veröffentlichen.

Da es eine der Aufgaben einer Grundlagenvorlesung ist, alle Studierende auf ein gleiches Bildungsniveau zu heben, könnte das eine oder andere Beispiel auch für Ihren Gymnasialunterricht von Interesse sein.

Wie üblich sind alle Beiträge MIT-lizensiert.

Viel Spaß damit!

**Comment by martin-pabst** [comment]
Vielen Dank! Ich bin gespannt!

**Comment by rozek** [comment]
Meine Studenten lernen inzwischen sogar, wie man mit Außerirdischen kommuniziert - entsprechende Programme habe ich gerade hochgeladen.
