### ISSUE TITLE
Integer.toString

### ISSUE THREAD

**Issue by rozek** [martin-pabst/Online-IDE#46]
Guten Morgen!

Ich habe gerade im Rahmen eines Beispiels für meine Studenten die Funktion `Integer.toString(n,2)` ausprobiert, um eine ganze Zahl in einen Binär-String umzuwandeln - dabei bleibt das Programm aber offenbar in der Funktion hängen...

```
println("before");
println(Integer.toString(123,2));
println("after");
```

**Comment by martin-pabst** [comment]
Guten Morgen Herr Rozek,
danke für die Fehlerbeschreibung! Der Fehler ist jetzt gefixt. Sie müssen die Online-IDE evtl. unter Umgehung des Browser-Cache neu laden (Chrome, Edge: Shift + F5), damit sicher die neueste Programmversion geladen wird.
Beste Grüße

Martin Pabst

**Comment by rozek** [comment]
Na das ging aber fix! Vielen Dank für Ihre Mühe!
