### ISSUE TITLE
List of languages that compile to JS

### ISSUE THREAD

**Issue by rozek** [martin-pabst/Online-IDE#47]
Auf [GitHub](https://github.com/jashkenas/coffeescript/wiki/List-of-languages-that-compile-to-JS) gibt es eine Liste von Programmiersprachen, die nach JavaScript übersetzt oder von einem in JS geschriebenen Interpreter ausgeführt werden. Im Abschnitt [Java/JVM](https://github.com/jashkenas/coffeescript/wiki/List-of-languages-that-compile-to-JS#javajvm) werden auch Java-Transpiler und -Interpreter geführt.

Möchten Sie Ihre Arbeit dort nicht auch eintragen? Sie wäre allemal einen Eintrag wert!

**Comment by Entkenntnis** [comment]
Ich hab die online-ide mal eingetragen und verlinkt (die Seite ist tatsächlich öffentlich bearbeitbar)

**Comment by martin-pabst** [comment]
Danke!
