### ISSUE TITLE
Web client randomly disconnects from the server

### ISSUE THREAD

**Issue by krakeen06** [martin-pabst/Online-IDE#49]
Looking at your last commits, I don't know whether the bug bash for this issue has already started. I'm facing the issue that using the Online-IDE, the client disconnects from the server without an apparent reason. It happens randomly every 10 - 20 minutes and to fix it, you have to reload the page, dismissing all your work that didn't have the chance to synchronize since the last server callback.

You can see that the client has been disconnected from the server by looking at the synchronization bar in the top right corner of the console which turns red. I wish there was a way to log this issue, but I can't seem to find any possibility regarding client logs.

Device: Windows 10 and 11, macOS Monterey 12.4, multiple Chrome versions (e. g. 101.0.4951.67)

**Comment by martin-pabst** [comment]
Thank you for reporting the error!

Unfortunately i wasn't able to reproduce the error yesterday evenening so i added extensive logging server- and clientside. I don't want to disturb service during school days therefore i'll wait till thursday before i update the server. Could you please test then and tell me what has been logged on console after the error occured?

**Comment by krakeen06** [comment]
Hello Martin, sorry for the late response, I've just happened to see your comment. 

I'm going to try and see whether I can reproduce the error now. After that, I'll send you the console output.

**Comment by krakeen06** [comment]
Okay, so I actually ended up working with the IDE today and I managed to reproduce the error.

The issue: The console has no output. I attached a screenshot of the console. In the top right corner you can see the red update indicator indicating that the connection to the server has been lost.

Maybe I'm looking at the wrong console? Or have you not pushed the logging function yet?

![error_onlineide](https://user-images.githubusercontent.com/51886322/170840586-b2eb3501-f703-4cf7-b740-f2e089f234fe.png)

**Comment by martin-pabst** [comment]
Thank you for testing!
Unfortunately i didn't realize that there are two consoles. Internal errors get logged on the browser's console. You can reach it by pressing F12 (developer tools) and then clicking on pane "console".
Could you please repeat your test tomorrow evening? I included additional logging today and will publish the new version tomorrow morning.

**Comment by krakeen06** [comment]
Thanks for the quick response. I'm going to test it tomorrow morning, as you said.

**Comment by krakeen06** [comment]
Okay, so I tested the logging yesterday evening and it spat out some inaccurate NetworkManager errors, but I didn't comment on that because you said there would be more logging capabilities starting today. 

Well, I have worked with the IDE today and ran into the issue. This time, the console output is much more accurate and although I have no idea about ts/js and the network management, it looks like you will be able to fix the issue with the log. 

`Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at _e.executeNode (Interpreter.ts:1282:38)
    at _e.nextStep (Interpreter.ts:807:30)
    at _e.timerFunction (Interpreter.ts:512:30)
    at Re.tick (World.ts:744:38)
    at TickerListener.Re.tickerFunction [as fn] (World.ts:551:18)
    at TickerListener.emit (ticker.js:100:22)
    at Ticker.update (ticker.js:481:37)
    at Ticker._tick (ticker.js:232:23)`

![image](https://user-images.githubusercontent.com/51886322/170863710-be4113e8-aad6-4e58-8565-a3042ac7ad30.png)

As always, I hope this was helpful. Thank you for your work!

**Comment by martin-pabst** [comment]
The error message "Servlet not allowed" is issued if the server assumes that user "Testuser" is logged in and wants to save files.

Did you have another browser tab open where you have been logged in as Testuser (by clicking on Button "Login als Testuser" at the login page)? This would explain this behaviour as browsers have a shared cookie store for browser tabs with the same URL-domain.
If you first log in with your credentials in browser tab A then a session cookie is stored. If you then login as Testuser in browser tab B then this cookie is overwritten by the session cookie of tab B.
If then the online-ide in tab A stores its files it presents this cookie to the server which then concudes that user Testuser wants to send the files.

**Comment by krakeen06** [comment]
Oh wow, I did actually always have a second tab open with the test user logged in. I never thought that could cause issues. Thanks for the explanation, it makes sense!

As I understand it, a workaround is to always first log in with the test user on the first tab and then open a second tab with the actual account so the session cookie of my actual accounts overwrites the test user credentials?

**Comment by martin-pabst** [comment]
Your workaround should work if i didn't overlook disabling all ajax requests from clients with Testuser logged in. More secure would be to use two different browsers (i.e. chrome and edge). 

There have been other incidents caused by cookie session storage as teachers often want to log in with their own account in one browser tab and with a student account in a second browser tab. I definitely must find a better way to store/transmit sessions.
