### ISSUE TITLE
Unable to close quick tips sometimes, close button out of display range

### ISSUE THREAD

**Issue by krakeen06** [martin-pabst/Online-IDE#50]
Sometimes, the close button for the quick tips in the Online-IDE is out of range. This renders the user unable to close the tip without reloading the page. See attached screenshot.

![image](https://user-images.githubusercontent.com/51886322/170863536-01b977a4-221c-4abf-b2a4-b2f223dde596.png)

**Comment by martin-pabst** [comment]
Thank you for reporting!
I reduced the width of the quick tips and set button alignment to center. This should fix the issue.
