### ISSUE TITLE
[Bug] Error when calling `destroy()` of a `Group`

### ISSUE THREAD

**Issue by Informa-Tiger** [martin-pabst/Online-IDE#52]
## When the bug occurs
It sometimes randomly occurs, when calling `destroy()` of an `Group` object,
or as reported by my classmate @Benedikt27, when calling `destroy()` of an element in a `Group`.

## Expected Behaviour
The complete group and all elements should be destroyed (or in my classmate's case the destroyed child removed) and the executed programme should continue to run.

## Bug

The execution of the programme stops, while the IDE still shows, that it is running. In the webconsole, the following error is thrown:
```
Uncaught Error: getChildAt: Index (0) does not exist.
    at Container.getChildAt (display.js:1570:19)
    at Container.removeChildAt (display.js:1619:26)
    at mt.deregister (Group.ts:454:46)
    at mt.remove (Group.ts:445:18)
    at st.destroy (Shape.ts:1187:33)
    at mt.destroyChildren (Group.ts:480:16)
    at mt.destroy (Group.ts:473:14)
    at k.invoke (Actor.ts:69:20)
    at _e.executeNode (Interpreter.ts:1099:46)
    at _e.nextStep (Interpreter.ts:807:30)
```

@Benedikt27 reported an error, where the wrong child disappeared, when calling `destroy()`, which caused an error as result of that.

## How to reproduce this bug
Well, unfortunately, I was not able to make a minimal example. It seemed a bit random to me, when exactly this error occurs.
I uploaded our whole school project [here](https://github.com/Informa-Tiger/online-ide-projects/tree/main/GameCollection11B) on GitHub, so that you can reproduce it.
For that you have to start the file `Main`, click on the `Spielen`-button to go to the game description and the click the green button to start the game.
When the ball leaves the view, the `View`-Object (`View` extends `Group`) of the game should be destroyed.
That is when the error occurs.

## Analysis
The error occurs in `Group.deregister`:
https://github.com/martin-pabst/Online-IDE/blob/db0bd5257f59f04cdad385c14714b9b55ae20012/src/client/runtimelibrary/graphics/Group.ts#L449-L466

It seems, that the order of the elements get mixed up, so that the order of `this.shapes` is not the same as of `this.displayObject.children`.
Thus when removing e.g. `this.shapes[0]` it will remove the wrong displayObject from `this.displayObject.children` ([line 454](https://github.com/martin-pabst/Online-IDE/blob/db0bd5257f59f04cdad385c14714b9b55ae20012/src/client/runtimelibrary/graphics/Group.ts#L454))
and after that add the right displayObject to `this.worldHelper.stage` in [line 462](https://github.com/martin-pabst/Online-IDE/blob/db0bd5257f59f04cdad385c14714b9b55ae20012/src/client/runtimelibrary/graphics/Group.ts#L462),
which automatically removes it from `this.displayObject.children`, so that it is empty now.
When the `Group` now tries to remove the remaining element of `this.shapes` there will be an error in line ([line 454](https://github.com/martin-pabst/Online-IDE/blob/db0bd5257f59f04cdad385c14714b9b55ae20012/src/client/runtimelibrary/graphics/Group.ts#L454)),
since `this.displayObject.children` is already ampty.

## Suggestion
I suggest changing ([line 454](https://github.com/martin-pabst/Online-IDE/blob/db0bd5257f59f04cdad385c14714b9b55ae20012/src/client/runtimelibrary/graphics/Group.ts#L454)) to

```typescript
        (<PIXI.Container>this.displayObject).removeChild(shapeHelper.displayObject);
```

This should fix the error, because `derigister` won't rely on having the lists in the same order anymore.

**Comment by martin-pabst** [comment]
Thank you for this error report! Your in-depth analysis was very helpful, especially your remark
"It seems, that the order of the elements get mixed up, so that the order of `this.shapes` is not the same as of `this.displayObject.children`". This was indeed the cause of the error.
I found out where the order got out of sync (`Shape.sendToBack` and `Shape.bringToFront`) and fixed the bug there. Additionally i followed your suggestion to alter line
```typescript
        (<PIXI.Container>this.displayObject).removeChild(shapeHelper.displayObject);
```
I would have searched for hours to find this bug. Thank you very much!
