### ISSUE TITLE
[Bug] CORS error when trying to access database

### ISSUE THREAD

**Issue by Informa-Tiger** [martin-pabst/Online-IDE#57]
## When the bug occurs
It occurs when trying to get a database connection from https://online-ide.de/.

## Expected Behaviour
Loading the database or throwing an error, if the access code isn't correct.

## Bug
The IDE holds on the line with the `DatabaseManager.getConnection` statement and shows, that it is loading the database, until you terminate the program.

## How to reproduce this bug
Go on https://online-ide.de/ and call `DatabaseManager.getConnection` with an valid access code.

## Analysis
In the web console you can see, that a CORS error occurs with the request to https://www.sql-ide.de/servlet/jGetDatabase.

## Suggestion
In the header of its response to the preflight request the https://www.sql-ide.de server allows only https://www.online-ide.de as `access-control-allow-origin`. I suggest adding the domain https://online-ide.de.

**Comment by martin-pabst** [comment]
Thank you very much, again!
I changed the webserver configuration to include https://online-ide.de in `access-control-allow-origin`-header.
