### ISSUE TITLE
Compiler doesn't allow calling interface method of an reference attribute

### ISSUE THREAD

**Issue by Entkenntnis** [martin-pabst/Online-IDE#60]
Hier ist ein kleines Code-Beispiel:

```java
interface MyInterface {
   public void myMethod();
}

class MyImplementation implements MyInterface {
   public void myMethod() {
      println("Hello");
   }
}

class TestClass {
   public MyInterface element;

   TestClass() {
      element = new MyImplementation();
   }

   public void testMethod() {
      element.myMethod();
   }
}

TestClass test = new TestClass();
test.testMethod(); // this works
test.element.myMethod(); // this fails, but should work
```

Bei der letzten Zeile meldet der Compiler leider folgendes: "Methodendefinitionen eines Interfaces können nicht statisch aufgerufen werden." - wenn man das Beispiel in JAVA nachprogrammiert, dann funktioniert die letzte Zeile.

Könnten Sie sich bei Gelegenheit diesen Fehler einmal anschauen und prüfen, was hier schief läuft? Vielen Dank!

**Comment by martin-pabst** [comment]
Thank you for reporting this bug!
