### ISSUE TITLE
Thread.sleep(int ms)

### ISSUE THREAD

**Issue by Entkenntnis** [martin-pabst/Online-IDE#63]
I am able to busy-wait with this class:

```java
class Thread {
   static void sleep(int ms) {
      int current = System.currentTimeMillis();
      while(System.currentTimeMillis() - current < ms) ;
   }
}
```

This is sufficient for my use case but I am wondering if there is a built-in way of doing this, e.g. `Thread.sleep(int ms)`? Maybe this would be a nice addition to the class library, because you can do animations like this without relying on `Actor`:

```java
Circle c = new Circle(300, 400, 1);

for (int i = 1; i < 1000; i++) {
   c.setRadius(i);
   Thread.sleep(20);
}
```

Feel free to close this issue if you are not planning to add this - the issue can still serve as a reference.

**Comment by martin-pabst** [comment]
There's `SystemTools.pause(int durationInMs);` for this purpose. I admit it's hard to find.
I'm planning to add threads later, therefore i didn't want to use the class identifier `Thread` for this purpose. All system functions which differ significantly from standard java are collected in the `SystemTools` class.

**Comment by Entkenntnis** [comment]
Nice! This is exactly what I was looking for.
