### ISSUE TITLE
getFontSize() of Text

### ISSUE THREAD

**Issue by Entkenntnis** [martin-pabst/Online-IDE#64]
Maybe I am overlooking something again, but I can set the font size with `setFontSize(double size)` but I haven't found a `getFontSize()` method in the class `Text`?

This is practical for statements like this:

```java
text.setFontSize(text.getFontSize() + 3);
```

I am using `scale()` at the moment, but the text is of course pixelated

**Comment by martin-pabst** [comment]
Good idea! I implemented the method.
