### ISSUE TITLE
Sometimes user password is broken

### ISSUE THREAD

**Issue by Entkenntnis** [martin-pabst/Online-IDE#65]
Hi Martin,

in diesem Schuljahr ist es schon 2x passiert, dass bei SchülerInnen auf einmal der Login nicht mehr funktioniert (Fehler 0002) - quasi über Nacht. Helfen tut dann leider nur noch das Zurücksetzen des Passworts.

Wir haben die offensichtlichen Sachen schon geklärt: Keine Versuche das Passwort zu ändern, Login am Rechner mit anderen Account geht, Passwort ist korrekt eingegeben ...

Evtl. ist Ihnen dieses Problem schon bekannt? Falls Sie nähere Details wissen wollen kann ich Ihnen die betreffenden Daten per Mail schicken.

**Comment by martin-pabst** [comment]
Hallo,
Fehler 0002 bedeutet, dass der Server entweder den username nicht finden konnte oder dass Passwort dazu nicht korrekt war. Falls Sie Daten dazu hätten, welche usernames betroffen waren und wann der Login nicht funktioniert hat, wäre ich dankbar. Vielleicht hilft das, dem Fehler auf die Spur zu kommen. Auf jeden Fall werde ich diesen Fehler jetzt mal mit zusätzlichen Daten vom Server loggen lassen.
Viele Grüße
Martin Pabst

**Comment by Entkenntnis** [comment]
Ich schließe das Issue, weil man im Moment nichts dazu tun kann (es ist nicht "actionable"). Ich melde mich, falls so ein Fehler wieder auftritt.
