### ISSUE TITLE
Can you clear the output screen?

### ISSUE THREAD

**Issue by Entkenntnis** [martin-pabst/Online-IDE#66]
I am currently writing a lot of code like this:

```java
Circle schneeball = new Circle(200, 500, 100);
// ...


// later

schneeball.destroy();
schneeball2.destroy();
schneeball3.destroy();
mund.destroy();
auge1.destroy();
auge2.destroy();
weihnachten.destroy();
```

I know that I could use Groups. But is there a way of destroying everything on the screen, like a static method `World.clear()`?

**Comment by martin-pabst** [comment]
You can set a default group to which subsequently all graphical objects are added automatically:
```
Group g = new Group();
g.getWorld().setDefaultGroup(g);

new Circle(200, 300, 100);
new Rectangle(10, 10, 400, 300);
// ...

// later
g.destroyAllChildren();
```

Your proposal (`World.clear()`) would indeed be useful. -> I'll try to implement it.

**Comment by martin-pabst** [comment]
Added World.clear()-method.
