### ISSUE TITLE
RuntimeLibrary: interface Map, wrong type in method put()

### ISSUE THREAD

**Issue by ralf1307** [martin-pabst/Online-IDE#7]
https://github.com/martin-pabst/Online-IDE/blob/5e0929288b19e6571f6140082686ec0f380f8db4/src/client/runtimelibrary/collections/Map.ts#L68

put should be (K key, V value), not (K key, K value)

Java-Doc: https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#put-K-V-

**Comment by martin-pabst** [comment]
Thank you!
-> fixed.
