### ISSUE TITLE
BUG - private Konstruktor

### ISSUE THREAD

**Issue by hvog** [martin-pabst/Online-IDE#71]
Es können Objekte erzeugt werden, obwohl der Konstruktor auf private gesetzt ist.
So kann das **Entwurfsmuster Singleton** in der Online-IDE nicht umgesetzt werden.
```
class Singleton 
{
   private Singleton()
   {
      println("Test");
   }

} 

Singleton s = new Singleton();
Singleton s2 = new Singleton();
Singleton s3 = new Singleton();
```

**Comment by martin-pabst** [comment]
Danke für den Hinweis!
