### ISSUE TITLE
Klasse Robot: Bug istWesten() und istOsten()

### ISSUE THREAD

**Issue by weichm** [martin-pabst/Online-IDE#72]
Folgendes Programm in der Online-IDE lässt ein Objekt der Klasse Robot solange links drehen, bis es nach Osten schaut:

```
Robot r = new Robot();

// Karol soll sich drehen, bis er nach Osten (also nach rechts) schaut
// er schaut aber nach Westen (also nach links)
while (! r.istOsten()) {
   r.linksDrehen();
}
```

Allerdings schaut Karol nach Ausführung des Programms nach Westen.
Ebenso wie `istOsten()` ist meiner Meinung nach auch `istWesten()` falsch implementiert.
`istNorden()` und `istSüden()` sind korrekt.

**Comment by martin-pabst** [comment]
Vielen Dank für die Fehlermeldung und das ausführliche Beispiel! Der Fehler ist jetzt behoben.
