### ISSUE TITLE
Monospaced font für includeIDE.js

### ISSUE THREAD

**Issue by weichm** [martin-pabst/Online-IDE#73]
Ich möchte die embedded-Version der Online-IDE gerne auf Mebis einbinden, wie auf https://www.embed.learnj.de/createwrapper.html beschrieben.
Allerdings wird der Code dort und in Moodle in einer proportionalen Schrift dargestellt, nicht monospaced, wie für Code üblich.

Ist das schwierig zu fixen?
Gibt es einen Workaround?

Danke!

**Comment by martin-pabst** [comment]
Das Problem mit der Schriftart liegt daran, dass Linux-Rechner die Schriften, die der Monaco-Editor vorsieht, allesamt nicht haben.
Ich habe das Skript includeIDE.js jetzt so erweitert, dass es die Schriftart Roboto Mono in verschiedenen Varianten lädt. Mein Test unter Debian Linux verlief positiv. Ich hoffe, bei Ihrem Rechner passt es jetzt auch. Falls nicht, geben Sie mir bitte Bescheid.
