### ISSUE TITLE
includeIDE.js and online-ide differ in version?

### ISSUE THREAD

**Issue by weichm** [martin-pabst/Online-IDE#74]
Für das (einfache) Programm `!false`  wird in der Online-IDE nur eine Info-Meldung ausgegeben (`"Der Wert dieses Terms wird zwar berechnet..."`), auf der Seite https://www.embed.learnj.de/createwrapper.html, welche `includeIDE.js` verwendet, wird das Programm als fehlerhaft beurteilt (`"! kann hier nicht verwendet werden"`).
Die Seite führt als Build-Date für `includeIDE.js` den 23.3.2023 auf.
Vielleicht besteht ein Zusammenhang mit https://github.com/martin-pabst/Online-IDE/commit/d208bd4c39d6d2f875fb52c280313be492b8d80e .
Learnj verwendet wohl einen neueren Build, da das Problem mit `!false` hier nicht auftritt.

Evtl. sind die Versionsstände von `includeIDE.js` und der entsprechenden Bibliothek der Online-IDE unterschiedlich?
Wird `includeIDE.js` immer neu gebaut, wenn ein Fehler in der Online-IDE gefixt wurde?
Wie ist die Zukunft von `includeIDE.js` oder wird nur noch die Online-IDE weiter entwickelt?

**Comment by martin-pabst** [comment]
Danke für den Hinweis!
Der Buildprozess für die Online-IDE findet clientseitig auf meinem Laptop statt, das Bauen des Archivs auf https://www.embed.learnj.de/createwrapper.html geschieht durch ein Shellscript auf dem Server und war bisher noch nicht vollständig automatisiert, daher habe ich diese Arbeit nur alle paar Wochen erledigt. Ich habe jetzt den kompletten Prozess automatisiert und das Starten des Serverskripts in den Buildprozess integriert, sodass die Version auf https://www.embed.learnj.de/createwrapper.html zukünftig nicht mehr hinterherhinken sollte.
