### ISSUE TITLE
Do not auto-focus the embedded editor

### ISSUE THREAD

**Issue by mikebarkmin** [martin-pabst/Online-IDE#76]
When using more than one embedded editor on a page, the last one will get the cursor and will auto focus. Im my case this leads to jumps on a page, after all editors are loaded. I would rather disable the auto focus feature, which should lead to a more consistant ui experience for my users.

**Comment by martin-pabst** [comment]
Thank you for reporting this bug! I fixed this bug by disabling editor focus on startup. Could you please test if the unwanted behaviour is gone now?

**Comment by mikebarkmin** [comment]
Everything is good, now. Thanks.
