### ISSUE TITLE
Declarations in Console are blocked

### ISSUE THREAD

**Issue by weichm** [martin-pabst/Online-IDE#77]
Hello,

I am trying to declare a `String` in "Console" directly, not by some programm file:

```
String a;
```

Problem is, `a` gets underlined by red waves, so that the instruction cannot be run.

Workaround is:

1. type `String a;` without pressing return
2. move cursor between `a` and `;` and type add `b`, so that the line now reads `String ab;`
3. press return

I interpret the problem as follows: syntax checker constructs parsing tree when `String a` is typed and immediately constructs `a`, if `;` is typed, syntax checker finds that `a` is already there in the parsing tree and therefore blocks execution. If I add `b`, I bypass this somehow. Don't know if this is true...

Weird description, I admit, if you need more infos, let me know.

**Comment by martin-pabst** [comment]
I'm sure i'll find a fix for this problem. Unfortunately i have not much time this week. Please have a little patience.

**Comment by martin-pabst** [comment]
Thank you for reporting! -> This bug is fixed.
