### ISSUE TITLE
two dimensional array visualization as graph

### ISSUE THREAD

**Issue by weichm** [martin-pabst/Online-IDE#79]
Hello,

I wonder if it would be possible to implement the following feature which would enable to visualize 2-dimensional arrays as graphs. Suppose `a` is given by

```
int[][] a = new int[][] { { 0, 1, 0, 1 }, { 1, 0, 0, 1 }, { 0, 1, 0, 1 }, { 1, 1, 1, 0 } };
```

In the screenshot below, magine a small button next to `a` in online-ide visualizing a graph symbol:
![image](https://github.com/martin-pabst/Online-IDE/assets/6342556/f18746c5-c83f-4684-b96b-24f071871ed9)

If you press this symbol, in a new browser window the graph gets layouted by e.g. `cola.js` (https://ialab.it.monash.edu/webcola/, MIT license).

What do you think?

**Comment by weichm** [comment]
Maybe it is more consistent with the current GUI if `cola.js` gets implemented as class, like `Circle`, `Rectangle`, `Robot`, `Hamster` or `JavaHamsterWorld` so that you can use this class to draw objects directly to the "Ausgabe"-window.

**Comment by martin-pabst** [comment]
I like your idea! 
I'm currently implementing a new Compiler from ground up, therefore i don't want to invest too much effort into new functionality using the current data structures. I added your feature request to the [feature request list on www.learnj.de](https://www.learnj.de/doku.php?id=javaonline:featurerequests#java-onlinefeature-requests).
