### ISSUE TITLE
Inputting @ inside the IDE causes a out of memory

### ISSUE THREAD

**Issue by ralf1307** [martin-pabst/Online-IDE#8]
Im not sure, but I think there is a loop inside Lexer.tx

**Comment by ralf1307** [comment]
I dont think we ever move to the next character.
https://github.com/martin-pabst/Online-IDE/blob/374263ffbaff9d610ec9b24ec4dea1d2f45446b7/src/client/compiler/lexer/Lexer.ts#L639

**Comment by martin-pabst** [comment]
Thank you! -> fixed.
