### ISSUE TITLE
Variables seen only after console input

### ISSUE THREAD

**Issue by weichm** [martin-pabst/Online-IDE#80]
Hello,

if I run the following output, I don't see any variables in the "variables"-window to the left:
![image](https://github.com/martin-pabst/Online-IDE/assets/6342556/6aa65499-ee60-4101-bef5-a869afc29156)

However, if I enter `a;` in the Console-Window, I get to see both `a` and `b` in the variables window:
![image](https://github.com/martin-pabst/Online-IDE/assets/6342556/380cb8cb-2cd5-49c4-8bdc-6ea8bd97ecc2)

Moreover, if I alter the programm (`a=1`) and run again, the variable `a` is not updated in the variables window:
![image](https://github.com/martin-pabst/Online-IDE/assets/6342556/3d4b0b45-6fdf-4a3a-b475-8bf15eb27cf5)

I think it would be best if both `a` and `b` appear in the variables window with the actual value once the program is run.

Thanks, Markus

**Comment by martin-pabst** [comment]
For performance reasons debugger output gets updated and program pointer is shown (as green bar) only if speed is lower than 15 steps/s or if the interpreter is in state "paused". Looking at your screenshot i guess that you expect correct values to be shown in state "program running" with speed == max.  
The online-ide's display "a == 0; b == 0" is clearly misleading as these values are not valid. I fixed this issue by blurring out the debugger-panels every time their display does not reflect the true state of the variables. Furthermore i increased the speed-limit up to which the debugger output gets updated an the program pointer is shown.

Please reload the online-ide without browser cache (Shift + F5 in chrome/edge) to see the new behaviour.

Is it better now?

**Comment by weichm** [comment]
Blurring out is a great idea. I checked and it works perfect, hence I close the issue.
Thank you for the quick fix!
