### ISSUE TITLE
if renamed, a folder loses all its workspaces after logout

### ISSUE THREAD

**Issue by weichm** [martin-pabst/Online-IDE#81]
Hello,

1. create some folder `000`
2. create some workspace `bla` in folder `000`
3. rename folder `000` to folder `001`
4. logout & login again

result: folder `001` has lost workspace `bla`, which is now in top-level directory. Workspace `bla` should have remained in folder `001`.

Thanks, Markus

**Comment by martin-pabst** [comment]
Thank you for reporting! 
I closed this issue prematurely, sorry. The bugfix is uploaded now.
