### ISSUE TITLE
Bug: Hamster.vornFrei() doesn't recognize empty cells

### ISSUE THREAD

**Issue by dorianignee** [martin-pabst/Online-IDE#84]
The method Hamster.vornFrei() doesn't recognize empty cells unless there are walls all around the JavaHamsterWorld.

Example:
The Hamster should walk all the way to the right end of its territory.
```
new HamsterBug().run();

class HamsterBug extends Hamster {
   HamsterBug() {
      super(new JavaHamsterWorld(10, 1), 0, 0, Hamster.OST, 0);
   }

   public void run() {
      while (vornFrei()) { // vornFrei returns false although there is space
         vor(); // if you run vor() without testing for vornFrei, an Exception is thrown:
         /*  
          * Fehler: Die neue Position (1, 0) ist außerhalb der Welt. Der Hamster kann daher nicht weitergehen.
          * Ort: run (Z 9, S 7)
          * aufgerufen von: Hauptprogramm (Z 1, S 18)
          */ 
      }
   }
}
```

Working example with walls around the territory:
```
new HamsterBug().run();

class HamsterBug extends Hamster {
   HamsterBug() {
      super(new JavaHamsterWorld(12, 3), 1, 1, Hamster.OST, 0);
      JavaHamsterWorld territory = getWorld();

      territory.init("""
      mmmmmmmmmmmm
      m          m
      mmmmmmmmmmmm
      """);
   }

   public void run() {
      while (vornFrei()) { // when there are walls all around the territory, vornFrei works as expected
         vor(); 
      }
   }
}
```

**Comment by martin-pabst** [comment]
Thank you for reporting this bug! It's now fixed.

Do you know happen to know how the original java hamster behaves if the hamster walks out of the world? Should it reappear at the other side (cyclic boundary condition) or should the program stop with an error message?

**Comment by dorianignee** [comment]
Thank you for fixing the bug. The original Hamster would recognize the world boundaries as walls and throws a MauerDaException when it tries to walk past the end of the world. 
![image](https://github.com/martin-pabst/Online-IDE/assets/83406502/847cff2e-feb6-4a22-9b3b-e5f779d7c644)

**Comment by martin-pabst** [comment]
Thank you!
I updated the code to conform to this behaviour.
