### ISSUE TITLE
Syntax Highlighting of Multiline Strings is broken

### ISSUE THREAD

**Issue by fischerling** [martin-pabst/Online-IDE#85]
If additional double quotes appear in a multiline string the syntax highlighting breaks.

See my screenshot below:

![20241229_15h43m52s_grim](https://github.com/user-attachments/assets/749eefa2-aac1-4b24-a0d6-1fb2eee85aca)

The compiler however does correctly lex the short reproducer.

The simple reproducer workspace is attached.

[Multiline String.json](https://github.com/user-attachments/files/18269928/Multiline.String.json)

**Comment by martin-pabst** [comment]
Thank you for reporting this bug!
-> Fixed.
